excluded: # paths to ignore during linting. Takes precedence over `included`.
  - .build
  - Pods/

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - todo
  - multiple_closures_with_trailing_closure
  - unused_optional_binding
  - implicit_getter
  - shorthand_operator
  - nesting
  - switch_case_alignment
  - orphaned_doc_comment
  - type_name
  - large_tuple
  - trailing_comma

opt_in_rules: # some rules are opt-in only
  - empty_count

analyzer_rules:
- unused_import

empty_count:
    severity: warning
force_cast: warning
force_try: warning
identifier_name:
    allowed_symbols: "_"
    excluded:
        - id
        - NO
        - ok
line_length:
    warning: 300
    error: 500
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 50
    error: 150
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 600
    error: 700
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 20
    error: 25
reporter: "xcode"
