excluded: # paths to ignore during linting. Takes precedence over `included`.  
  - .build
  - Pods/

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - force_cast
  - todo
  - multiple_closures_with_trailing_closure
  - cyclomatic_complexity
  - file_length
  - unused_optional_binding
  - implicit_getter
  - shorthand_operator
  - nesting
  - switch_case_alignment
  - orphaned_doc_comment
  - type_name
  - large_tuple
  - trailing_comma

analyzer_rules:
- unused_import

empty_count: 
    severity: warning
force_cast: warning
force_try: warning
identifier_name:
    allowed_symbols: "_"
    excluded:
        - id
        - NO
        - ok
line_length:
    warning: 180
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 50
    error: 150
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
